/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as DemoSettingsRouteImport } from './routes/demo/settings'
import { Route as DemoHistoryRouteImport } from './routes/demo/history'
import { Route as DemoAnalyticsRouteImport } from './routes/demo/analytics'
import { Route as AppUpgradeRouteImport } from './routes/app/upgrade'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppMapRouteImport } from './routes/app/map'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppAgentRouteImport } from './routes/app/agent'
import { Route as AppPasturesIdRouteImport } from './routes/app/pastures/$id'
import { Route as AppAgentRunIdRouteImport } from './routes/app/agent.$runId'

const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const DemoSettingsRoute = DemoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DemoRoute,
} as any)
const DemoHistoryRoute = DemoHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAnalyticsRoute = DemoAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DemoRoute,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppPasturesIdRoute = AppPasturesIdRouteImport.update({
  id: '/pastures/$id',
  path: '/pastures/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRunIdRoute = AppAgentRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => AppAgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/subscribe': typeof SubscribeRoute
  '/app/agent': typeof AppAgentRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/map': typeof AppMapRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/demo/analytics': typeof DemoAnalyticsRoute
  '/demo/history': typeof DemoHistoryRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/app/': typeof AppIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/app/agent/$runId': typeof AppAgentRunIdRoute
  '/app/pastures/$id': typeof AppPasturesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/subscribe': typeof SubscribeRoute
  '/app/agent': typeof AppAgentRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/map': typeof AppMapRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/demo/analytics': typeof DemoAnalyticsRoute
  '/demo/history': typeof DemoHistoryRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/app': typeof AppIndexRoute
  '/demo': typeof DemoIndexRoute
  '/app/agent/$runId': typeof AppAgentRunIdRoute
  '/app/pastures/$id': typeof AppPasturesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/subscribe': typeof SubscribeRoute
  '/app/agent': typeof AppAgentRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/map': typeof AppMapRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/demo/analytics': typeof DemoAnalyticsRoute
  '/demo/history': typeof DemoHistoryRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/app/': typeof AppIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/app/agent/$runId': typeof AppAgentRunIdRoute
  '/app/pastures/$id': typeof AppPasturesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/sign-in'
    | '/subscribe'
    | '/app/agent'
    | '/app/analytics'
    | '/app/history'
    | '/app/map'
    | '/app/onboarding'
    | '/app/settings'
    | '/app/upgrade'
    | '/demo/analytics'
    | '/demo/history'
    | '/demo/settings'
    | '/app/'
    | '/demo/'
    | '/app/agent/$runId'
    | '/app/pastures/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/subscribe'
    | '/app/agent'
    | '/app/analytics'
    | '/app/history'
    | '/app/map'
    | '/app/onboarding'
    | '/app/settings'
    | '/app/upgrade'
    | '/demo/analytics'
    | '/demo/history'
    | '/demo/settings'
    | '/app'
    | '/demo'
    | '/app/agent/$runId'
    | '/app/pastures/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/sign-in'
    | '/subscribe'
    | '/app/agent'
    | '/app/analytics'
    | '/app/history'
    | '/app/map'
    | '/app/onboarding'
    | '/app/settings'
    | '/app/upgrade'
    | '/demo/analytics'
    | '/demo/history'
    | '/demo/settings'
    | '/app/'
    | '/demo/'
    | '/app/agent/$runId'
    | '/app/pastures/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  SignInRoute: typeof SignInRoute
  SubscribeRoute: typeof SubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/demo/settings': {
      id: '/demo/settings'
      path: '/settings'
      fullPath: '/demo/settings'
      preLoaderRoute: typeof DemoSettingsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/history': {
      id: '/demo/history'
      path: '/history'
      fullPath: '/demo/history'
      preLoaderRoute: typeof DemoHistoryRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/analytics': {
      id: '/demo/analytics'
      path: '/analytics'
      fullPath: '/demo/analytics'
      preLoaderRoute: typeof DemoAnalyticsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/app/upgrade': {
      id: '/app/upgrade'
      path: '/upgrade'
      fullPath: '/app/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent': {
      id: '/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pastures/$id': {
      id: '/app/pastures/$id'
      path: '/pastures/$id'
      fullPath: '/app/pastures/$id'
      preLoaderRoute: typeof AppPasturesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent/$runId': {
      id: '/app/agent/$runId'
      path: '/$runId'
      fullPath: '/app/agent/$runId'
      preLoaderRoute: typeof AppAgentRunIdRouteImport
      parentRoute: typeof AppAgentRoute
    }
  }
}

interface AppAgentRouteChildren {
  AppAgentRunIdRoute: typeof AppAgentRunIdRoute
}

const AppAgentRouteChildren: AppAgentRouteChildren = {
  AppAgentRunIdRoute: AppAgentRunIdRoute,
}

const AppAgentRouteWithChildren = AppAgentRoute._addFileChildren(
  AppAgentRouteChildren,
)

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRouteWithChildren
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppMapRoute: typeof AppMapRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPasturesIdRoute: typeof AppPasturesIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRouteWithChildren,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppMapRoute: AppMapRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUpgradeRoute: AppUpgradeRoute,
  AppIndexRoute: AppIndexRoute,
  AppPasturesIdRoute: AppPasturesIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DemoRouteChildren {
  DemoAnalyticsRoute: typeof DemoAnalyticsRoute
  DemoHistoryRoute: typeof DemoHistoryRoute
  DemoSettingsRoute: typeof DemoSettingsRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAnalyticsRoute: DemoAnalyticsRoute,
  DemoHistoryRoute: DemoHistoryRoute,
  DemoSettingsRoute: DemoSettingsRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  SignInRoute: SignInRoute,
  SubscribeRoute: SubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
